# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=90)),
                ('cat_url', models.CharField(max_length=60)),
                ('parent_id', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=200)),
                ('click_count', models.IntegerField()),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_desc', models.TextField(blank=True, null=True)),
                ('goods_thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_img', models.CharField(blank=True, max_length=255, null=True)),
                ('add_time', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.category')),
            ],
        ),
    ]
